all:
	(cd battery_info && $(MAKE)) >/dev/null
	(cd network_load && $(MAKE)) >/dev/null
	(cd network_info && $(MAKE)) >/dev/null
	(cd location && $(MAKE)) >/dev/null
	(cd spaces_count && $(MAKE)) >/dev/null
	(cd popup_context && $(MAKE)) >/dev/null
	(cd system_stats && $(MAKE)) >/dev/null
	(cd menus && $(MAKE)) >/dev/null
